backend:
  name: git-gateway
  branch: master
media_folder: public/img
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - label: "Articles"
    name: "articles"
    folder: "content/articles"
    create: true
    slug: "{{custom-slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Slug", name: "custom-slug", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
